### PR TITLE
feat: add touchpad information from input

### PR DESCRIPTION
**Pull request by jeffshuai**
some proc file handle no mouse may miss touchpad

Log: add touchpad information from input

### CODE REVIEW

**Comment by xzl01** [comment]
需要以patch的形式修改上游内容

**Review by UTsweetyfish — CHANGES_REQUESTED** [review]
Thanks for your contribution! But..
1. Please do not change code directly. Instead please use quilt patch.
2. Please bump changelog. Here you need to bump to `21.82-2deepin1`, for example.

**Comment by UTsweetyfish** [comment]
https://github.com/openSUSE/hwinfo/pull/139/

**Comment by UTsweetyfish** [comment]
I would rather wait for upstream response to see their response.

稍微提醒一下，可能需要代码格式化一下

**Pull request merged**
