### PR TITLE
fix: just for v20 dpkg build

### PR DESCRIPTION
**Pull request by jeffshuai**
just for v20 dpkg build

Log: just for v20 dpkg build

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Comment by Zeno-sole** [comment]
@jeffshuai  这个包需要在v20上集成么？

**Pull request closed without merging**
